### ISSUE TITLE
Compatibility Issues between Cowboy 2.11.0 and PlugCowboy v2.7.0: Understanding and Resolving Header Handling Conflicts

### ISSUE THREAD

**Issue by eric0fw** [elixir-plug/plug_cowboy#98] opened 2024-03-13 10:30 UTC
After updating to Cowboy version 2.11.0, compatibility issues have arisen with plug_cowboy version 2.7.0, leading to failures in environments where plug_cowboy requests the latest version of Cowboy. This issue manifests specifically when running mix phx.create, resulting in an application that crashes on initial load with a header handling error related to set-cookie directives.

As identified by a Cowboy maintainer, the root cause of this issue stems from Cowboy's recent update to be more explicit in what is not allowed concerning the set-cookie header. The way Plug sets the set-cookie header does not comply with the HTTP specification, as Cowboy cannot handle it like other headers due to its special nature. Previously, this incompatibility did not surface due to coincidental factors but has now become evident with Cowboy's stricter enforcement.

Can we get a proper fix for [it](https://github.com/ninenines/cowboy/issues/1639)?

**Comment by eric0fw** [comment] 2024-03-13 10:35
Is [this](https://github.com/elixir-plug/plug_cowboy/commit/a3877c46c80890de18bd6e79bd91ef537e4b7e30) the fix, and when can we expect 2.7.1?

**Comment by josevalim** [comment] 2024-03-13 10:45
Yes, this is a duplicate of the pinned #95. Please give main a try and, if it works as expected, we can ship a new release.

**Closed by josevalim** 2024-03-13 10:45 UTC

**Comment by josevalim** [comment] 2024-03-13 11:00
> The way Plug sets the set-cookie header does not comply with the HTTP specification

Btw, this is inaccurate. The way Plug set the headers is completely valid and follows the HTTP specification. We do the same as Cowboy (which is to accumulate the cookies separately) and set the header. We never mixed the header and Cowboy resp cookies. I understand why Cowboy wants to close down their APIs but, at the same time, we always adhered to the HTTP spec because we never mixed them.

**Comment by esambo** [comment] 2024-04-08 20:25
It looks like 2.7.1 was released
